### ISSUE TITLE
Ajouter les caméras 

### ISSUE THREAD

**Issue by vegeta0911** [Minims/MyFox2MQTT#1]
Bonjour
Je viens d’installer la mise à jour est tout fonctionne très bien je peu maintenant armer ou désarmer mon alarme. Je viens voir aussi qu’il a remonté tout mes devices.

Je te remercie beaucoup d’avoir pris le temps pour résoudre mon problème.

je viens de m’apercevoir que il y a pas des historiques d’évènements, parce que j’aimerais faire notification avec les évènements (exemple intrusion ou pile h.s etc …), par contre j’ai bien l’état de l’alarme (armer et désarmer).
Et en bonus avoir la caméra 😍

si tu veux de l’aide vu que j’ai cette alarme on peu être ce trouver un créneau si tu veux ?

**Comment by Minims** [comment]
J'ai ajouté une entité MQTT text en alpha avec des historiques en 2023.9.2 , car je ne vois toujours pas comment bien intégrer ça correctement..

**Comment by Minims** [comment]
Tu dois avoir l'historique fonctionnel dans la 2023.10.0. 

Pour les camera, c'est toujours d'actualité. On peut essayer de les intégrer ?

**Comment by vegeta0911** [comment]
Ok je vais test ça la semaine prochaine merci encore 👍

Le 26 sept. 2023 à 21:17, Minims ***@***.***> a écrit :

﻿

Tu dois avoir l'historique fonctionnel dans la 2023.10.0.

Pour les camera, c'est toujours d'actualité. On peut essayer de les intégrer ?

**Comment by Minims** [comment]
Renommage de l'issue sur m'integration des camera uniquement.
