### ISSUE TITLE
Question API / Déclenchement alarme 

### ISSUE THREAD

**Issue by idjul** [Minims/MyFox2MQTT#12]
Salut Minims,

Est-ce que l'API MyFox renvoie quelque chose quand l'alarme est déclenchée ? 
Je pose la question car si c'était le cas, les scénarios seraient infinis.
Je n'ai rien trouvé dans la doc de l'API de MyFox en ce sens, mais je me dis que ça doit être possible car il est possible de créer des recettes IFTTT si l'alarme est déclenchée

Merci

EDIT: infos trouvées sur IFTTT, ça peut peut-être aider : https://ifttt.com/myfox_homecontrol/triggers/alert_intrusion

**Comment by Minims** [comment]
Hello,

Aucune idée, je me base sur https://api.myfox.me/dev/documentation  et je ne possède pas cette alarme.
Je suppose qu'il y a quelque chose dans l'historique dans ce cas ?

**Comment by idjul** [comment]
Oui exact :

<img width="896" alt="Capture d’écran 2023-10-03 à 21 35 04" src="https://github.com/Minims/MyFox2MQTT/assets/36371545/b10b133a-e36b-41e0-be77-a3e67b9d5688">

**Comment by Minims** [comment]
Donc il faudrait que l'alarme passe en trigered quand on voit passer ce message dans l'historique ?

**Comment by idjul** [comment]
Ouais, en gros le but serait peut être de pouvoir créer des automations basé sur les "types" de messages qui sont les suivants :

<img width="129" alt="Capture d’écran 2023-10-03 à 22 08 36" src="https://github.com/Minims/MyFox2MQTT/assets/36371545/3fcbccec-efc4-4edf-9476-f26e0b6bd532">

On pourrait imaginer un sensor qui reprend les messages ?

**Comment by Minims** [comment]
On pourrait mais j'ai toujours un problème dans HA c'est quel sensor fait ca.
Cat on recupere:
 - une date
 - un type d'event
 - le message associé.
Et il faut que ce soit configurable en MQTT

**Comment by idjul** [comment]
Les messages arrivent déjà dans le log de l'add-on

`2023-10-13 09:18:46,416 [INFO] [myfox.api:586] Site History: {'status': 'OK', 'timestamp': 1697181526, 'payload': {'items': [{'logId': 828967751, 'label': 'Désactivation de la protection depuis internet', 'type': 'security', 'createdAt': '2023-10-13T04:00:00Z'}, {'logId': 828983429, 'label': 'Activation totale de la protection depuis internet', **'type': 'security', 'createdAt': '2023-10-13T06:00:00Z'}, {'logId': 828990521, 'label': 'Alarme « Intrusion » déclenchée par votre Détecteur de mouvement « 1er Etage ».', 'type': 'alarm', 'createdAt': '2023-10-13T06:32:36Z'}**, {'logId': 828990547, 'label': 'Désactivation de la protection depuis internet', 'type': 'security', 'createdAt': '2023-10-13T06:32:47Z'}]}}`

**Comment by Minims** [comment]
Oui ca je sais et il y a une entité mqtt.text avec le dernier event. Le soucis est de comment retranscrire ces infos dans un type d’entité HA

**Comment by idjul** [comment]
Alors si tu parles de l'entité text.myfox_hc2_home_history, chez moi, rien ne se met dedans

**Comment by Minims** [comment]
j'ai refait une correction dans la version dev sur cette entité, a voir si c'est mieux.

**Comment by idjul** [comment]
Hello

Je viens de tester, effectivement, à l'initialisation l'état se met bien
dans text, mais quand on active et désactive l'alarme, l'entité ne se met
pas à jour

**Comment by Minims** [comment]
meme après 1 a 2 minutes l'état ne se met pas à jour ??

**Comment by Minims** [comment]
Nouvelle version a tester https://github.com/Minims/MyFox2MQTT/releases/tag/2023.11.0

**Comment by idjul** [comment]
Hello,

Malheureusement, toujours pareil

**Comment by Minims** [comment]
A tester avec la dernière version : 2024.9.2

**Comment by Minims** [comment]
je dirais avec un truc du genre : 

```
value_template: {{ "intrusion" in states('text.*****') }}

```

**Comment by idjul** [comment]
Au top, ça fonctionne parfaitement, merci pour ton aide !
