### ISSUE TITLE
Capteur luminosité et température

### ISSUE THREAD

**Issue by xavax59** [Minims/MyFox2MQTT#13]
Bonjour, 
J'ai bien la température qui remonte sur le capteur de température et luminosité mais pas la luminosité. 
Est ce possible de l'ajouter ?
Merci

**Comment by Minims** [comment]
Hello,

Ca doit être possible, je le met sur la liste

**Comment by Minims** [comment]
J'ai  fait un test sur la version de dev a tester.

**Comment by xavax59** [comment]
ca y est j'ai pu tester, ca donne ceci : 

![image](https://github.com/Minims/MyFox2MQTT/assets/54884656/218a9e59-4373-4eed-8e5c-5ad55a4a77be)

**Comment by Minims** [comment]
tu as quoi dans les logs sur cette ligne ? 
```
Devices Light:
```

**Comment by xavax59** [comment]
`Devices Light: {'status': 'OK', 'timestamp': 1697894732, 'payload': {'items': [{'deviceId': 28376, 'label': 'Capteur de Température', 'light': '2', 'modelId': 29, 'modelLabel': 'Capteur température & luminosité'}]}}`

**Comment by Minims** [comment]
Je viens de faire une correction sur la version dev pour ce soucis, dis moi si c'est mieux.

**Comment by idjul** [comment]
Pas mieux, l'info ne remonte pas et la valeur de la température est fausse
<img width="580" alt="Capture d’écran 2023-10-22 à 17 29 57" src="https://github.com/Minims/MyFox2MQTT/as
<img width="332" alt="Capture d’écran 2023-10-22 à 17 31 48" src="https://github.com/Minims/MyFox2MQTT/assets/36371545/9182199d-93c8-42a2-b766-2dff29b4d30d">
sets/36371545/4ddaeeee-1ac3-4241-b004-280a643435aa">

**Comment by Minims** [comment]
J'ai fait une nouvelle correction, si tu peux essayer stp

**Comment by xavax59** [comment]
oui ca remonte, par contre j'ai toujours la commande level, j'ai supprimé l'équipement au cas ou mai ca remonte qd meme .
<img width="331" alt="image" src="https://github.com/Minims/MyFox2MQTT/assets/54884656/c5d762a2-7f9c-4ab2-ba1e-186330770b0f">

**Comment by idjul** [comment]
Essaies de supprimer l'entrée MQTT et reconstruis l'add-on, il ne remonte pas chez moi.

<img width="322" alt="Capture d’écran 2023-10-23 à 21 33 17" src="https://github.com/Minims/MyFox2MQTT/assets/36371545/35181f63-9902-4657-9ae0-2ccea6217183">

**Comment by xavax59** [comment]
oui j'ai refait la manip c'est bon pour moi

**Comment by idjul** [comment]
Je confirme que c'est ok @Minims 
Voici ce que ça donne :

<img width="583" alt="Capture d’écran 2023-10-24 à 20 03 19" src="https://github.com/Minims/MyFox2MQTT/assets/36371545/46004222-afdc-49c0-8ba4-bb9b6f288fa6">

**Comment by Minims** [comment]
Merci pour le retour.

Nouvelle version dispo: https://github.com/Minims/MyFox2MQTT/releases/tag/2023.10.2
