### ISSUE TITLE
demande de « correction sur fonction close volet RTS »

### ISSUE THREAD

**Issue by winnibouba** [Minims/MyFox2MQTT#14]
Bonjour
J'utilise myfox2mqtt pour pouvoir piloter la centrale myfox et ses équipements sur jeedom. Merci pour le super boulot que vous avez réalisé
Sur jeedom, j'utilise le plugin MQTT Discovery et pour pouvoir piloter la fonction stop des volets roulants, il faudrait d'après le dev du plugin, réaliser une petite modif dans myfox2mqtt car il y a une petit erreur dans la config pour tous les volets.
Selon les specs de mqtt discovery cela devrait être la clé pl_cls au lieu de pl_close (ou alors payload_close si ce n’est pas abrégé), pl_open et pl_stop sont correctes
**exemple ici :**
`"22687_1022057": {
            "shutter": {
                "config": {
                    "name": "shutter",
                    "unique_id": "1022057_shutter",
                    "device": {
                        "identifiers": [
                            1022057
                        ],
                        "manufacturer": "MyFox",
                        "model": "Motorisation RTS (beta)",
                        "name": "Coin nuit",
                        "sw_version": "Unknown"
                    },
                    "pl_open": "open",
                    "pl_close": "close",
                    "pl_stop": "my",
                    "optimistic": "true",
                    "command_topic": "myfox2mqtt\/22687\/1022057\/shutter\/command"
                }
            }
        }`

Serait il possible de faire la modif pour pouvoir piloter entièrement les volets ?

Merci beaucoup

**Comment by Minims** [comment]
Hello,

C'est corrigé en version `dev`.

Si c'est Ok je ferais la release.

**Comment by Minims** [comment]
Nouvelle version dispo: https://github.com/Minims/MyFox2MQTT/releases/tag/2023.10.2

**Comment by winnibouba** [comment]
Ça marche nickel
Merci,,👍
