### ISSUE TITLE
mise à jour info history qui ne se met plus à jour

### ISSUE THREAD

**Issue by winnibouba** [Minims/MyFox2MQTT#18]
Bonjour

depuis 1 ou 2 jours, l'info des historiques de l'alarme ne se met plus à jour correctement
je vois bien sur mqtt explorer que l'info se met bien à jour mais  l’info qu'envoie myfox2mqtt n'est pas la dernière

voici ce que j'ai comme dernière mise à jour de myfox2mqtt 
![c9c86398f485cdf380c973200ac25972023d6a7c](https://github.com/Minims/MyFox2MQTT/assets/147975777/349c7b49-ed11-4171-a092-f55ea0d0281f)
et dans l'application myfox, on voit que les infos suivantes n'ont pas été remontée
![Screenshot_2023-11-01-14-50-01-178_com myfox homecontrol](https://github.com/Minims/MyFox2MQTT/assets/147975777/cbe86d77-f40a-4e98-b2c6-214fdc38a581)

**Comment by xavax59** [comment]
Idem pour moi, ca repete toujours la meme info : 
![image](https://github.com/Minims/MyFox2MQTT/assets/54884656/a30080e7-9181-4fa1-bf21-4782756a55af)

**Comment by Minims** [comment]
Nouvelle version a tester https://github.com/Minims/MyFox2MQTT/releases/tag/2023.11.0

**Comment by winnibouba** [comment]
Ça semble bien fonctionner après quelques tests
Merci beaucoup 👍

**Comment by idjul** [comment]
Chez moi c'est toujours non fonctionnel

**Comment by Minims** [comment]
Je ne sais pas comment aider ici. Est ce qu'une personne qui utilise ce plugin avec JEEDOM peut aider ?
Je suppose que tu utilises l'image sur dockerhub. en dernière version ?

**Comment by winnibouba** [comment]
Regarde ce post  
https://community.jeedom.com/t/myfox-et-jedom-4-4/111828

**Comment by Minims** [comment]
Fix des dates dans la 2024.9.1
