### ISSUE TITLE
Perte de connection 

### ISSUE THREAD

**Issue by jerem76** [Minims/MyFox2MQTT#20]
J’ai une prête de connexion sur ha os, je doit reboot l’intégration pour retrouver la fonctionnalité 

versions ha 
Core 2024.2.3
Supervisor 2024.03.0
Operating System 11.5

Myfox intergration

2023.11.0

**Comment by Minims** [comment]
Hello, Ok je pensais qu'il s'agissait de SomfyProtect, je vais regarder si j'ai mis les meme mécanismes sur MyFox2MQTT.

**Comment by Minims** [comment]
Tu as des logs quand l'addon ne fonctionne plus ? Dsl je ne peux pas tester, je n'ai pas cette alarme.

**Comment by jerem76** [comment]
hello, merci de ta réponse.

Je vais essayer de retrouver la date à laquelle j’ai perdu la connexion.
Sinon je t’envoie un mail lorsque ça ne fonctionne plus avec les log

Encore merci pour ton développement hyper utile
