### ISSUE TITLE
Problème historique

### ISSUE THREAD

**Issue by chsalmon** [Minims/MyFox2MQTT#23]
Bonjour,

D'abord merci pour ce plugin.
Il n'est pas encore pleinement activé chez moi , je suis en phase de migration jeedom -> HA, donc encore sous jeedom en prod...
Tout semble parfaitement fonctionner, sauf un petit bug dans l'historique a priori.

Je ne sais pas comment modifier le plugin dans HA pour tester une éventuelle correction alors je te donne mon analyse du problème :

En fait la date reçue par Myfox (MyFox HC2) est au format UTC : 

{"logId":871132103,"label":"Lancement du sc\u00e9nario \u00ab DesactiveVirtuel1SurAlarme \u00bb","type":"scenario","createdAt":"2024-09-06T16:48:18Z"},
{"logId":871153527,"label":"Lancement du sc\u00e9nario \u00ab VirtuelDesactiveAlarmeJeedom \u00bb","type":"scenario","createdAt":"2024-09-06T20:00:08Z"}

les deux évènements on été reçue à 18h18:18  et 22h00:08  heure locale.

Je pense que quand tu filtres les évènements avant 90 secondes tu ne tiens pas compte du décalage : 

```  
Dans Business :  def update_sites_status(  api: MyFoxApi,    mqtt_client: MQTTClient,    mqtt_config: dict,    my_sites_id: list,)

created_at = event.get("createdAt")
 date_format = "%Y-%m-%dT%H:%M:%SZ"
 created_at_date = datetime.strptime(created_at, date_format)
  now = datetime.now()
 if now - created_at_date < timedelta(seconds=90):
     recuperation de l'event...
```

dans les logs HA, juste apres l'évenement de 22h, on ne le récupère pas : 

2024-09-06 22:00:38,213 [INFO] [business:407] Event is too old scenario 2024-09-06T16:48:18Z Lancement du scénario « DesactiveVirtuel1SurAlarme »
**2024-09-06 22:00:38,213 [INFO] [business:407] Event is too old scenario 2024-09-06T20:00:08Z Lancement du scénario « VirtuelDesactiveAlarmeJeedom »**

J'imagine que tu sais gérer ce genre de calcul de date, au cas où, si ça peut aider, j'avais eu le meme problème pour un appel API transilien... j'ai utilisé cette méthode : 

```
def datetime_from_utc_to_local(utc_datetime):
    now_timestamp = time.time()
    offset = datetime.datetime.fromtimestamp(now_timestamp) -   datetime.datetime.utcfromtimestamp(now_timestamp)
    return utc_datetime + offset


heureUTC = datetime.datetime.strptime(heureArrivee, "%Y-%m-%dT%H:%M:%S.%fZ")
heureLocale=datetime_from_utc_to_local(heureUTC)
```

Je me demande s'il ne faudrait pas au moins garder le dernier évènement si tous les évènements sont trop vieux, histoire d'avoir au moins un évènement. 
Où alors avoir un attribut "LastHistory" (dernier evenement de l'historique )

Merci.

**Comment by Minims** [comment]
Hello, 

J'ai ajouté une correction rapide sur la branch dev. 
Si tu utilises l'addon tu peux installer celui de dev pour tester.

Je n'ai rien testé car je n'ai pas de compte. Dis moi si ca fonctionne.

Pour ce point je ne sais pas comment le representé dans HA, dis moi si tu as une idée.

> Je me demande s'il ne faudrait pas au moins garder le dernier évènement si tous les évènements sont trop vieux, histoire d'avoir au moins un évènement.
Où alors avoir un attribut "LastHistory" (dernier evenement de l'historique )

**Comment by chsalmon** [comment]
salut,

Petit bug : 

```
2024-09-08 11:08:54,013 [INFO] [myfox.api:586] Site History: {'status': 'OK', 'timestamp': 1725786533, 'payload': {'items': [{'logId': 871333903, 'label': 'Lancement du scénario « VirtuelDesactiveAlarmeJeedom »', 'type': 'scenario', 'createdAt': '2024-09-08T09:08:27Z'}]}}
2024-09-08 11:08:54,036 [WARNING] [business:422] Error while getting site history: can't subtract offset-naive and offset-aware datetimes
```

(Heure historique myfox 11h08:27 )


Pour LastHistory , je n'ai pas vraiment d'idée, ça serait une simple chaine de caractère. 
Mais elle serait renvoyée à chaque itération, je ne maitrise pas assez HA ou mqtt pour savoir si c'est possible ou pas.
T'embêtes pas avec ça, j'ai pas de besoin avec, c'était juste une idée :-)

Merci.

**Comment by Minims** [comment]
J’ai fait une modif, retente. Si tu as mis l’addon dev, il faut cliquer sur reconstruire

**Comment by chsalmon** [comment]
C'est bon ça fonctionne !
Merci.

Pour info, tu sais  a combien on peut descendre les délais d'appel des api myfox ?  Ils ne bloquent pas si on fait trop d'appel ? Si on met 10 secondes ça passe ? 
(il me semble qu'il y avait ça dans le paramètre de dev, mais j'ai changé à 60 secondes au cas où )

**Comment by chsalmon** [comment]
En fait le LastHistory existe déjà puisque le dernier envoyé n'est pas supprimé...
Je pensais que la zone History était vidée si il n'y a pas d'historique mais en fait non, aucun message n'est envoyé a mqtt donc la zone est renseignée avec le dernier évènement.
Tout est bon donc !

**Comment by Minims** [comment]
> Pour info, tu sais a combien on peut descendre les délais d'appel des api myfox ? Ils ne bloquent pas si on fait trop d'appel ? Si on met 10 secondes ça passe ?

Je ne sais pas. mais je conseille de ne pas descendre sous les 60 secondes pour éviter d'etre blacklisté ou pire qu'il soit demandé de retirer l'addon.
Je corrige le code pour mettre la limitation, je ne l'avais fait que sur somfyprotect2mqtt.

**Comment by chsalmon** [comment]
Ok merci.

Il reste un "10 secondes" pour les devices dans le code  (myfox_2_mqtt.py)

```
self.delay_site = config.get("delay_site", 60)
self.delay_site = max(self.delay_site, 60)

self.delay_device = config.get("delay_device", 60)
self.delay_device = max(self.delay_device, 10)
```

**Comment by Minims** [comment]
Merci, j’ai corrigé. Si tu as pas de soucis dans les prochains jour je ferais le release de l’addon.

**Comment by chsalmon** [comment]
Ok, merci.

**Comment by Minims** [comment]
Nouvelle version lancée. l'image devrait dispo sous peu
