### ISSUE TITLE
Entité text.myfox_hc2_home

### ISSUE THREAD

**Issue by idjul** [Minims/MyFox2MQTT#3]
Hello,

J'ai l'impression qu'une nouvelle entité est crée : text.myfox_hc2_home
Elle génère beaucoup de pollution au niveau des logs 

Possible de l'exclure ?

Merci

**Comment by Minims** [comment]
Hello,
Oui je peux toujours la retirer. 
Mais je veux bien voir les logs que ca genere pour savoir si je peux corriger plutôt que de retirer cette partie.

**Comment by idjul** [comment]
Hello

Voici ce que j'ai dans le logbook

<img width="1184" alt="Capture d’écran 2023-09-07 à 21 13 06" src="https://github.com/Minims/MyFox2MQTT/assets/36371545/2f509d5a-ddbc-4442-b308-d4dba9d7c83f">

**Comment by Minims** [comment]
Ok ca publie toujours la même chose. Je vais regarder pour ne publier que les nouveaux événements.

**Comment by Minims** [comment]
2023.9.3 publié, ca devrait limité fortement ce comportement.

**Comment by idjul** [comment]
Je confirme, c’est nickel maintenant merci

**Comment by Minims** [comment]
Fix Inclut dans la release 2023.10.0.
