### ISSUE TITLE
action mqtt Jeedom ?

### ISSUE THREAD

**Issue by xavax59** [Minims/MyFox2MQTT#4]
Bonjour, j'ai reussi a avoir les retour d'etat de mon alarme en MQTT dans jeedom,  par contre je ne sais pas du tout comment envoyer des actions. Il faut mettre quoi dans le topic MQTT et le playload ? 
Un grand merci pour ce projet qui me permets de continuer a garder mon alarme.

**Comment by Minims** [comment]
Les actions sont : 
```
    partial
    disarmed
    armed
```

et il faut l'envoyer dans le topic : 
```
myFox2mqtt/{site.siteId}/command
```

**Comment by xavax59** [comment]
<img width="1696" alt="image" src="https://github.com/Minims/MyFox2MQTT/assets/54884656/5547d9f3-2958-4451-8889-016937c15cdc">
merci je pense que ca fonctionne.
{site.siteId} c'est bien 1271 dans mon cas c'est ca ?

**Comment by Minims** [comment]
> {site.siteId} c'est bien 1271 dans mon cas c'est ca ?

Oui :-)

**Comment by xavax59** [comment]
Oui les commandes fonctionnent bien pour armer désarmer etc
Je n’ai pas encore trouvé comment exécuter un scénario myfox 

et je ne comprends pas à quoi correspondent ces commandes
