### ISSUE TITLE
intégration des scénarios ? 

### ISSUE THREAD

**Issue by xavax59** [Minims/MyFox2MQTT#5]
Bonjour,
Est il possible d'integrer les scnénarios myfox dans le plug in ? Ca permettrait de déclencher les sirenes depuis HA par exemple. 
Sur myfox il n'est possible de declencher les sirenes que depuis un scnéario. 
<img width="1040" alt="image" src="https://github.com/Minims/MyFox2MQTT/assets/54884656/d2ddc7aa-2022-4c4f-b26a-67a86445ade4">
Merci

**Comment by Minims** [comment]
Hello, 

Surement. tu sais me dire ce que tu as dans tes logs pour : 
```
[INFO] [myfox.api:398] Scenarios
```

Tu utilises l'addon HA ou tu le lances manuellement ?

**Comment by xavax59** [comment]
J'utilises l'addon HA, mais je débute sur HA. c'est bien ca qu'il te faut ? 
`2023-09-19 21:10:20,599 [INFO] [myfox.api:398] Scenarios: {'status': 'OK', 'timestamp': 1695150620, 'payload': {'items': [{'scenarioId': 120625, 'label': 'Armement partiel', 'typeLabel': 'onDemand', 'enabled': None}, {'scenarioId': 144029, 'label': 'Allumage abreuvoir', 'typeLabel': 'onDemand', 'enabled': None}, {'scenarioId': 171979, 'label': 'ALERTE', 'typeLabel': 'onDemand', 'enabled': None}, {'scenarioId': 120623, 'label': 'Armement Total', 'typeLabel': 'onDemand', 'enabled': None}, {'scenarioId': 1196, 'label': 'camera ON / detection fumee', 'typeLabel': 'onEvent', 'enabled': True}, {'scenarioId': 2069, 'label': 'Caméra ON Intrusion', 'typeLabel': 'onEvent', 'enabled': True}]}}`

**Comment by Minims** [comment]
J'ai fait un patch, je ne sais pas si ca fonctionne

Il existe maintenant une version (dev) de l'addon si tu refraichis les mises à jour. 

- Installe la
- met la meme configuration que sur l'addon de production
- coupe l'addon de production
- demarre celui de dev
- dis moi s'il y a des erreurs dans les logs
- Normalement tu devrais avoir des boutons dans l'alarm pour jouer des scenarios.

**Comment by Minims** [comment]
> J'ai reussi a installer la version dev, par contre je ne vois pas mes scénarios dans les entités. Si j'ai un scénario nqui s'appelle ALERTE je suis censé retrouver le meme nom ?

Oui,

je viens de faire un correctif, fais RECONSTRUIRE sur l'addon de dev pour etre a jour.

dis moi aussi ce qu'il y a dans le log 'Found Scenario'

**Comment by xavax59** [comment]
voici : 
`2023-09-20 08:45:45,966 [INFO] [business:75] Found Scenario Armement partiel: 120625
2023-09-20 08:45:45,967 [INFO] [business:75] Found Scenario Allumage abreuvoir: 144029
2023-09-20 08:45:45,968 [INFO] [business:75] Found Scenario ALERTE: 171979
2023-09-20 08:45:45,968 [INFO] [business:75] Found Scenario Armement Total: 120623
2023-09-20 08:45:45,969 [INFO] [business:75] Found Scenario camera ON / detection fumee: 1196
2023-09-20 08:45:45,970 [INFO] [business:75] Found Scenario Caméra ON Intrusion: 2069`

**Comment by Minims** [comment]
Ok jusque la c’est Ok. Tu vois toujours pas de nouveau boutons dans l’appareil MyFox alarme ? 

Pas de warning ou error dans le log de l’addon ?

**Comment by xavax59** [comment]
Je ne vois pas d'erreur, j'ai relancé HA au cas ou, lorsque je fais dans entité et que je te ALERTE (nom d'un scénario) je n'ai rien qui apparait.

**Comment by xavax59** [comment]
par contre je ne sais pas si c'est lié mais j'ai un scénario qui apparait ici

<img width="1047" alt="image" src="https://github.com/Minims/MyFox2MQTT/assets/54884656/505a58de-036c-45eb-852b-c837ea545217">

**Comment by Minims** [comment]
bizarre, j'ai fait une correction, fais mise à jour et reconstruire.
Est ce que tu vois tous les scenarios maintenant ?

**Comment by xavax59** [comment]
ca fonctionne ! ils apparaissent. PAr contre lorsque je veux les executer ca ne fonctionne pas . 
<img width="1694" alt="image" src="https://github.com/Minims/MyFox2MQTT/assets/54884656/f45cfab3-ff77-4c7c-ae13-42b4189927e7">
<img width="325" alt="image" src="https://github.com/Minims/MyFox2MQTT/assets/54884656/bc568279-8982-44d4-991c-fa6b79373d25">

**Comment by Minims** [comment]
J’ai fais une mise a jour essaye de nouveau stp

**Comment by xavax59** [comment]
ca fonctionne ! j'ai executé un scénario il apparait bien dans mon hsitorique Myfox. 
Juste un truc, il y a plusieurs types de scénarios dans jeedom, ceux qu'on executer à la demande donc avec un click, ceux qui sont automatisé par un déclencheur type capteur de porte (du coup on ne peux pas les demarrer a la demande et des périodiques. 
Dans HA ils ont tous les fonction pour les demarrer à la demande mais en fait ca ne peut fonctionner qu'avec ceux type "à la demande"

<img width="321" alt="image" src="https://github.com/Minims/MyFox2MQTT/assets/54884656/fc3ba551-d5e4-4f06-8ce1-8ca1105973eb">
ici les scénarios  camera On sur... ne peuvent pas etre actionné manuellement et pourtant j'ai le bouton appuyer sur HA. 
Apres c'est du detail au pire il suffit de masquer l'entité. En tout c'est top ca fonctionne. reste a voir si c'est possible de faire la meme chose avec les prises :)
Encore merci

**Comment by Minims** [comment]
Ok je fais filter sur `'typeLabel': 'onDemand' `

Est ce que tu peux effacer l'appareil complet avant la prochaine mise a jour pour qu'il soit recréer proprement dans HA.
Je ne peux pas facilement effacé ceux qui ont été ajouté en trop.

**Comment by xavax59** [comment]
ok j'essaye de faire ca, je ne sais pas trop comment on supprime les périphérique dans ha

**Comment by Minims** [comment]
C'est dans les 3 points verticaux a cote de MQTT INFO. Tu as Supprimer l'appareil.

J'ai fait le fix, tu peux essayer, normalement tu auras que les onDemand

**Comment by xavax59** [comment]
<img width="321" alt="image" src="https://github.com/Minims/MyFox2MQTT/assets/54884656/6ecbe3ab-49b4-4cad-98e7-99b966d108b6">
nickel ca fonctionne

**Comment by Minims** [comment]
Inclut dans la release 2023.10.0.
