### ISSUE TITLE
integration des automatismes ? 

### ISSUE THREAD

**Issue by xavax59** [Minims/MyFox2MQTT#6]
Bonjour, j'ai des prises intégrées dans myfox, elles remontent bien dans HA mais je ne sais pas comment faire pour les piloter. 
<img width="1230" alt="image" src="https://github.com/Minims/MyFox2MQTT/assets/54884656/5c2a8719-8207-427e-9add-c0265e471aea">
La prise apparait comme ceci. 
En fait j'ai l'impression quelle apparait comme un element de securité comme pour un capteur de porte que l'on peut activer selon le mode de l'alarme. Ce n'est pas le cas sur Myfox. Sur myfox je n'ai que du ON OFF ou la possibilité de l'intégrer dans un scénario
<img width="1230" alt="image" src="https://github.com/Minims/MyFox2MQTT/assets/54884656/a112f862-a269-4416-a07e-88906ffdd83a">
Si ce n'est pas possible de l'integrer comme une prise dans le plug in, j'essayerai de l'intégrer dans un scénario myfox lorsque les scénarios seront pilotables depuis le plug in sur HA
Merci

**Comment by Minims** [comment]
Je regarde ca une fois que les scenarios seront fonctionnels

**Comment by Minims** [comment]
Nouvelle version dev dispo pour tester les sockets.

**Comment by Minims** [comment]
@xavax59 tu as pu tester les prises ?

**Comment by xavax59** [comment]
je viens de regarder, je n'avais pas vu ton message hier je ne sais pas pourquoi je n'ai pas eu de notifications
a priori ca doit fonctionner mais je ne peux pas tester car je ne suis pas chez moi pour controler l'allumage de la prise...
<img width="1029" alt="image" src="https://github.com/Minims/MyFox2MQTT/assets/54884656/46d48b51-2bbe-426e-bd62-4829afa91c44">
en tout cas les commandes sont la 
par contre c'est possible de supprimer celles qui ne servent pas ? armed partial etc ?

**Comment by Minims** [comment]
Possible Oui, mais c'est normalement des valeurs configurable pour l'alarme.

tu as quoi dans ton log pour la partie socket ici:
```
[INFO] [myfox.api:291] Devices: 
```

**Comment by xavax59** [comment]
depuis l'interface myfox on ne peut pas parametrer l'etat d'un automatisme selon l'etat de l'alarme. O nne peut faire ce que sur la partie alarme (capteur ir , ouverture etc... )
depuis myfox je peux juste parametrer le nom 
<img width="874" alt="image" src="https://github.com/Minims/MyFox2MQTT/assets/54884656/d10ad2b6-ccbe-4306-ad41-f42ce3e9cde6">
si je veux activer une prise selon l'etat de l'alarme ca doit passer par un scénario
Voici les logs :
`2023-09-22 08:42:53,150 [INFO] [myfox.api:291] Devices: {'status': 'OK', 'timestamp': 1695364973, 'payload': {'items': [{'device_id': 19926841874, 'label': 'Centrale', 'device_definition': {'device_definition_id': 1, 'device_definition_label': 'Myfox HC2'}, 'settings': {'global': {'exit_delay': 10, 'jamming_detection_enabled': True, 'silent_mode_enabled': False}}, 'created_at': '2012-12-26 14:17:46'}, {'device_id': 1534, 'label': '2 Baie vitrée gauche', 'device_definition': {'device_definition_id': 9, 'device_definition_label': 'Capteur TAG'}, 'settings': {'global': {'sensitivity': 7}, 'armed': {'enabled': True}, 'partial': {'enabled': True}, 'disarmed': {'enabled': False}}, 'created_at': '2012-12-26 15:18:46'}, {'device_id': 1535, 'label': 'detecteur fumée cellier', 'device_definition': {'device_definition_id': 12, 'device_definition_label': 'Détecteur de fumée'}, 'settings': {'armed': {'enabled': False}, 'partial': {'enabled': False}, 'disarmed': {'enabled': False}}, 'created_at': '2012-12-26 15:29:14'}, {'device_id': 3293, 'label': '2 boutons', 'device_definition': {'device_definition_id': 23, 'device_definition_label': 'Télécommande 2 boutons'}, 'settings': {'armed': {'enabled': False}, 'partial': {'enabled': False}, 'disarmed': {'enabled': False}}, 'created_at': '2013-01-12 09:17:22'}, {'device_id': 3298, 'label': 'infrarouge Salon', 'device_definition': {'device_definition_id': 13, 'device_definition_label': 'Détecteur de mouvement'}, 'settings': {'armed': {'enabled': True}, 'partial': {'enabled': False}, 'disarmed': {'enabled': False}}, 'created_at': '2013-01-12 09:35:14'}, {'device_id': 23466, 'label': '4 Fenêtre entrée', 'device_definition': {'device_definition_id': 9, 'device_definition_label': 'Capteur TAG'}, 'settings': {'global': {'sensitivity': 8}, 'armed': {'enabled': True}, 'partial': {'enabled': True}, 'disarmed': {'enabled': False}}, 'created_at': '2013-06-21 16:19:44'}, {'device_id': 28376, 'label': 'Capteur de Température', 'device_definition': {'device_definition_id': 29, 'device_definition_label': 'Capteur température & luminosité'}, 'settings': {'armed': {'enabled': False}, 'partial': {'enabled': False}, 'disarmed': {'enabled': False}}, 'created_at': '2013-07-22 14:21:07'}, {'device_id': 28677, 'label': 'Porte Chalet de Jardin', 'device_definition': {'device_definition_id': 10, 'device_definition_label': 'Capteur TAG Contact'}, 'settings': {'armed': {'enabled': True}, 'partial': {'enabled': True}, 'disarmed': {'enabled': True}}, 'created_at': '2013-07-24 14:55:02'}, {'device_id': 80615, 'label': 'télécommande 4 boutons', 'device_definition': {'device_definition_id': 31, 'device_definition_label': 'Télécommande 4 boutons'}, 'settings': {'armed': {'enabled': False}, 'partial': {'enabled': False}, 'disarmed': {'enabled': False}}, 'created_at': '2014-02-21 17:10:37'}, {'device_id': 80710, 'label': 'Jardin Optex 1', 'device_definition': {'device_definition_id': 10, 'device_definition_label': 'Capteur TAG Contact'}, 'settings': {'armed': {'enabled': True}, 'partial': {'enabled': True}, 'disarmed': {'enabled': False}}, 'created_at': '2014-02-22 09:15:09'}, {'device_id': 112917, 'label': 'infrarouge garage', 'device_definition': {'device_definition_id': 13, 'device_definition_label': 'Détecteur de mouvement'}, 'settings': {'armed': {'enabled': True}, 'partial': {'enabled': True}, 'disarmed': {'enabled': False}}, 'created_at': '2014-06-30 08:47:58'}, {'device_id': 114525, 'label': 'Jardin optex 2', 'device_definition': {'device_definition_id': 10, 'device_definition_label': 'Capteur TAG Contact'}, 'settings': {'armed': {'enabled': False}, 'partial': {'enabled': False}, 'disarmed': {'enabled': False}}, 'created_at': '2014-07-05 13:25:24'}, {'device_id': 121154, 'label': '9 fenetre cellier', 'device_definition': {'device_definition_id': 9, 'device_definition_label': 'Capteur TAG'}, 'settings': {'global': {'sensitivity': 8}, 'armed': {'enabled': True}, 'partial': {'enabled': True}, 'disarmed': {'enabled': False}}, 'created_at': '2014-07-26 17:59:52'}, {'device_id': 134882, 'label': 'Sonnette', 'device_definition': {'device_definition_id': 10, 'device_definition_label': 'Capteur TAG Contact'}, 'settings': {'armed': {'enabled': True}, 'partial': {'enabled': False}, 'disarmed': {'enabled': True}}, 'created_at': '2014-09-11 18:05:57'}, {'device_id': 142243, 'label': '3 porte cellier', 'device_definition': {'device_definition_id': 9, 'device_definition_label': 'Capteur TAG'}, 'settings': {'global': {'sensitivity': 8}, 'armed': {'enabled': True}, 'partial': {'enabled': False}, 'disarmed': {'enabled': False}}, 'created_at': '2014-10-08 19:07:10'}, {'device_id': 150952, 'label': "Porte d'entrée", 'device_definition': {'device_definition_id': 54, 'device_definition_label': 'IntelliTAG'}, 'settings': {'global': {'sensitivity': 9}, 'armed': {'enabled': True}, 'partial': {'enabled': True}, 'disarmed': {'enabled': False}}, 'created_at': '2014-11-05 20:10:39'}, {'device_id': 297735, 'label': 'Prises terrasse', 'device_definition': {'device_definition_id': 15, 'device_definition_label': 'Module encastrable'}, 'settings': {'armed': {'enabled': False}, 'partial': {'enabled': False}, 'disarmed': {'enabled': False}}, 'created_at': '2015-07-07 16:41:44'}, {'device_id': 412375, 'label': 'relais sirene', 'device_definition': {'device_definition_id': 7, 'device_definition_label': "Sirène d'intérieur"}, 'settings': {'armed': {'enabled': False}, 'partial': {'enabled': False}, 'disarmed': {'enabled': False}}, 'created_at': '2015-11-28 07:37:27'}, {'device_id': 510751, 'label': 'cumulus innondation', 'device_definition': {'device_definition_id': 27, 'device_definition_label': 'Détecteur de panne de congélateur'}, 'settings': {'armed': {'enabled': False}, 'partial': {'enabled': False}, 'disarmed': {'enabled': False}}, 'created_at': '2016-04-09 16:46:35'}, {'device_id': 636033, 'label': 'porte cuisine', 'device_definition': {'device_definition_id': 54, 'device_definition_label': 'IntelliTAG'}, 'settings': {'global': {'sensitivity': 8}, 'armed': {'enabled': True}, 'partial': {'enabled': True}, 'disarmed': {'enabled': False}}, 'created_at': '2016-10-22 17:40:57'}, {'device_id': 933427, 'label': 'Palier', 'device_definition': {'device_definition_id': 12, 'device_definition_label': 'Détecteur de fumée'}, 'settings': {'armed': {'enabled': False}, 'partial': {'enabled': False}, 'disarmed': {'enabled': False}}, 'created_at': '2018-12-10 16:41:53'}, {'device_id': 933429, 'label': 'Cave', 'device_definition': {'device_definition_id': 12, 'device_definition_label': 'Détecteur de fumée'}, 'settings': {'armed': {'enabled': False}, 'partial': {'enabled': False}, 'disarmed': {'enabled': False}}, 'created_at': '2018-12-10 16:49:48'}, {'device_id': 944689, 'label': 'sirene exterieure', 'device_definition': {'device_definition_id': 8, 'device_definition_label': "Sirène d'extérieur"}, 'settings': {'armed': {'enabled': False}, 'partial': {'enabled': False}, 'disarmed': {'enabled': False}}, 'created_at': '2019-01-19 07:56:32'}, {'device_id': 1056117, 'label': 'sirene interieure exterieure', 'device_definition': {'device_definition_id': 7, 'device_definition_label': "Sirène d'intérieur"}, 'settings': {'armed': {'enabled': False}, 'partial': {'enabled': False}, 'disarmed': {'enabled': False}}, 'created_at': '2020-12-31 16:11:59'}, {'device_id': 1062025, 'label': 'Fenetre salon', 'device_definition': {'device_definition_id': 54, 'device_definition_label': 'IntelliTAG'}, 'settings': {'global': {'sensitivity': 8}, 'armed': {'enabled': True}, 'partial': {'enabled': True}, 'disarmed': {'enabled': False}}, 'created_at': '2021-02-16 08:52:04'}, {'device_id': 1062027, 'label': 'Fenetre séjour', 'device_definition': {'device_definition_id': 54, 'device_definition_label': 'IntelliTAG'}, 'settings': {'global': {'sensitivity': 7}, 'armed': {'enabled': True}, 'partial': {'enabled': True}, 'disarmed': {'enabled': False}}, 'created_at': '2021-02-16 09:11:49'}, {'device_id': 1062029, 'label': 'Fenetre cuisine', 'device_definition': {'device_definition_id': 54, 'device_definition_label': 'IntelliTAG'}, 'settings': {'global': {'sensitivity': 8}, 'armed': {'enabled': True}, 'partial': {'enabled': True}, 'disarmed': {'enabled': False}}, 'created_at': '2021-02-16 09:23:02'}, {'device_id': 1093259, 'label': 'Baie droite', 'device_definition': {'device_definition_id': 54, 'device_definition_label': 'IntelliTAG'}, 'settings': {'global': {'sensitivity': 7}, 'armed': {'enabled': True}, 'partial': {'enabled': True}, 'disarmed': {'enabled': False}}, 'created_at': '2021-12-05 17:35:33'}, {'device_id': 1148513, 'label': 'Télécommande Secours', 'device_definition': {'device_definition_id': 31, 'device_definition_label': 'Télécommande 4 boutons'}, 'settings': {'armed': {'enabled': False}, 'partial': {'enabled': False}, 'disarmed': {'enabled': False}}, 'created_at': '2023-09-14 15:37:16'}, {'device_id': 1148911, 'label': 'Prise Poulailler', 'device_definition': {'device_definition_id': 18, 'device_definition_label': 'Prise électrique commandée'}, 'settings': {'armed': {'enabled': False}, 'partial': {'enabled': False}, 'disarmed': {'enabled': False}}, 'created_at': '2023-09-19 15:42:32'}]}}`

**Comment by Minims** [comment]
Je peux regarder pour nettoyer mais peut etre plus simple de désactiver.

ces 3 paramètres sont bien dans la configuration du relais.

 {'device_id': 297735, 'label': 'Prises terrasse', 'device_definition': {'device_definition_id': 15, 'device_definition_label': 'Module encastrable'}, 'settings': {'armed': {'enabled': False}, 'partial': {'enabled': False}, 'disarmed': {'enabled': False}}, 'created_at': '2015-07-07 16:41:44'},

**Comment by xavax59** [comment]
Oui on peut laisser comme ca ce n'est pas génant.

**Comment by Minims** [comment]
Inclut dans la release 2023.10.0.
