### ISSUE TITLE
problems d'accents dans l'historique

### ISSUE THREAD

**Issue by xavax59** [Minims/MyFox2MQTT#7]
Bonjour, 
C'est encore moi, j'ai remarqué un problème d'accent dans l'historique
`Changé en "security 2023-09-20T09:44:27Z D\u00e9sactivation de la protection depuis internet"`
C'est possible de faire en sorte qu'il y ait les accents ? 
<img width="551" alt="image" src="https://github.com/Minims/MyFox2MQTT/assets/54884656/40bfbed6-5759-4b64-86a2-eafaf7446650">
J'ai regardé dans les logs du plug in il y a bien les accents. 
`2023-09-20T19:18:01.116584332Z 2023-09-20 19:18:01,115 [INFO] [myfox.api:555] Site History: {'status': 'OK', 'timestamp': 1695237481, 'payload': {'items': [{'logId': 825731283, 'label': 'Désactivation de la protection depuis internet', 'type': 'security', 'createdAt': '2023-09-20T04:49:12Z'}, {'logId': 825748565, 'label': 'Activation totale de la protection par la télécommande « télécommande 4 boutons »', 'type': 'security', 'createdAt': '2023-09-20T06:32:47Z'}, {'logId': 825772029, 'label': 'Désactivation de la protection depuis internet', 'type': 'security', 'createdAt': '2023-09-20T09:44:27Z'}, {'logId': 825772101, 'label': 'Activa
`

**Comment by Minims** [comment]
J'ai essayé encoder en UTF-8 dans la payload MQTT, a voir si ca fonctionne.
Version dev a jour

**Comment by xavax59** [comment]
c'est bien ici que je suis censé voir l'hsitorique ? 
<img width="349" alt="image" src="https://github.com/Minims/MyFox2MQTT/assets/54884656/fcb4f0d3-ca3f-41ef-8b13-5f348991ec49">
ca reste sur unknow

**Comment by xavax59** [comment]
dans les logs pourtant je le vois bien 

`label': 'Activation partielle de la protection depuis internet', 'type': 'security', 'createdAt': '2023-09-20T21:01:14Z'}]}}
2023-09-20 23:01:22,357 [INFO] [myfox.api:158] Site Status: {'status': 'OK', 'timestamp': 1695243682, 'payload': {'status': 2, 'statusLabel': 'partial'}}
2023-09-20 23:01:22,357 [INFO] [business:360] Update 1271 Status`

**Comment by Minims** [comment]
Il faut que l'event ait moins d'une minute pour que je l'affiche. donc au demarrage il peut ne pas en avoir.

**Comment by xavax59** [comment]
c'est bien ici que je dois retouver l'historique ? 
<img width="1040" alt="image" src="https://github.com/Minims/MyFox2MQTT/assets/54884656/da404bee-1cfe-406c-bf2c-25f8d2c4b5d5">
avant je voyais alarme activé depusi internet etc... la je ne le retrouve plus je ne sais pas pourquoi

**Comment by Minims** [comment]
Je viens de faire un correctif, ce devrait etre bon pour les accents maintenant

**Comment by xavax59** [comment]
chez moi ca ne remonte plus 
<img width="898" alt="image" src="https://github.com/Minims/MyFox2MQTT/assets/54884656/a0cf2a9b-2d09-4ba3-8a08-2f0ae838e2b4">
j'ai changé l'etat de l'alarme apres avoir reconstruit et ca ne remonte pas

**Comment by xavax59** [comment]
Bonjour, tu as bien reçu mes réponses ? Bonne soirée

**Comment by Minims** [comment]
Hello, 

oui mais je  n´ai pas eu le temps de regarder. Et je ne vois pas pkoi ca ne fonctionne pas pour l’instant.

tu as essayé de reconstruire a nouveau ?

**Comment by xavax59** [comment]
J'ai testé et c'est reparti apres avoir reconstruit a nouveau mais par contre j'ai toujours ceci 
`"security 2023-09-26T06:29:04Z Activation totale de la protection par la t\u00e9l\u00e9commande \u00ab t\u00e9l\u00e9commande 4 boutons \u00bb"`
<img width="583" alt="image" src="https://github.com/Minims/MyFox2MQTT/assets/54884656/64a2dc49-c92f-4493-a551-85bae46e3d08">

**Comment by Minims** [comment]
Y a un truc pas clair. 
Bon j'ai release la 2023.10.0. 
Refait les tests sur la version de production, normalement c'est ok.

**Comment by xavax59** [comment]
J'ai tout rebooté, et ca fonctionne ! merci !

**Comment by vegeta0911** [comment]
bonjour 

je viens tester la nouvelle version la release 2023.10.0.
j'ai le même problème xavax59 j'ai le statut inconnu pourtant dans les logs tout semble bien fonctionner:
![Mosquitto](https://github.com/Minims/MyFox2MQTT/assets/67876957/518e1e34-ea09-4695-924e-d51467e246c5)
![myfox2mqtt](https://github.com/Minims/MyFox2MQTT/assets/67876957/ca6ccb24-d976-4ed1-9ef1-3f5793a64bad)
![MQTT](https://github.com/Minims/MyFox2MQTT/assets/67876957/8c013a03-dd6a-4416-92f0-ac3e3b28a838)

merci d'avance de pouvoir éclairer ma lanterne :)

**Comment by xavax59** [comment]
Ce qui est étrange c’est que j’ai installé la dernière stable et intégré sur jeedom en mqtt et la j’ai tout comme il faut. Je me demande si ce n’est pas un blocage dans l’historique de la commande HA mais je n’ai pas trouvé comment la réinitialiser

**Comment by Minims** [comment]
Au pire tu effaces l'appareil de MQTT dans HA et relance l'addon, ca va tout recréé.
La partie History ne fonctionne que s'il récupère un message et que le message a  moins de 70 sec.
J'ai aussi activé le `retain` sur MQTT pour history pour que l'entité ne soit plus en inconnu lors du redémarrage.

**Comment by vegeta0911** [comment]
je viens de tout supprimer les appareils dans mqtt et je me suis reco et il m'a réinstallé tout, mais j'ai toujours le texte inconnu.

j'ai fait ça il y a même pas heure.

**Comment by Minims** [comment]
et si tu actives et désactives ton alarme,  attends 70s, est ce que  ca se met a jour ?

**Comment by vegeta0911** [comment]
pour le test de activer l'alarme ou de le désactiver, je test demain car la ma femme est a la maison et pas moi lol

**Comment by vegeta0911** [comment]
je viens de tester en activant mon alarme : 
![Capture](https://github.com/Minims/MyFox2MQTT/assets/67876957/a71c8416-6809-43e3-8372-75bdf7d1c841)
mais le problème il le stock car il arrive surement pas a les envoyers.

**Comment by xavax59** [comment]
Je ne sais pas si le problème peut venir de la, mais quelqu'un ma fait remarqué que : la commande pour l’état de l’alarme et la commande pour l’historique ont le même identifiant et le même nom
Ca ne peut pas poser de problème ca dans HA ? Car sur jeedom en mqtt j'ai bien les infos mais sur HA ca ne fonctionne pas

**Comment by Minims** [comment]
Hum bien vu, j'ai fait pousser une correction dans la version dev.

**Comment by xavax59** [comment]
c'est ok pour moi

**Comment by Minims** [comment]
Ajouté dans la version 2023.10.1

**Comment by vegeta0911** [comment]
Je viens d’installer la nouvelle mise à jour la 2023.10.1, mais toujours le message inconnu je n’arrive pas cerner le problème quelqu’un pourrais m’aider ?

**Comment by xavax59** [comment]
moi aussi ca fait ca ...
![image](https://github.com/Minims/MyFox2MQTT/assets/54884656/216e39ef-876c-4d43-be95-e2da79a44e3b)

**Comment by xavax59** [comment]
ce qui est bizarre c'est que c'est un peu aléatoire.
![image](https://github.com/Minims/MyFox2MQTT/assets/54884656/8a084588-4c59-46e9-a3e7-5135761e4220)

**Comment by vegeta0911** [comment]
Et passant par node red pour récupérer la valeur ?

**Comment by xavax59** [comment]
pourquoi par node red ? 
Ce qui est vraiment bizarre c'est que sur docker et jeedom j'ai bien tout dans le log. 
![image](https://github.com/Minims/MyFox2MQTT/assets/54884656/6495a210-8d08-411a-9d8c-cc9495b4f11f)

**Comment by xavax59** [comment]
Quelqu'un m'a fait remarqué que le plug in envoyait sur 2 topics differents Myfox2mqtt et parfois sur myfox2mqtt
Ca ne peut pas pas de la le problème ?

**Comment by Minims** [comment]
Je vais regarder tout ca  que j’ai un peu plus de temps

**Comment by Minims** [comment]
tu sais me dire coque tu reçois dans le topic Myfox2mqtt ou myfox2mqtt (celui qui en reçoit le moins) histoire de voir ou ca peut foirer car pareil je vois rien de bizarre dans le code a 1ere vue.

**Comment by Minims** [comment]
Soucis d'accès corrigé. Je clos.Je poursuis sur https://github.com/Minims/MyFox2MQTT/issues/12 pour les soucis de mise a jour de l'historique
