### ISSUE TITLE
comande motion_sensor

### ISSUE THREAD

**Issue by xavax59** [Minims/MyFox2MQTT#9]
Bonjour, 
j'ai une question concernant l'intégrations des tags, j'ai compris toutes les commandes qui etaient intégrées sauf une 
porte_d_entree_motion_sensor
A quoi correspond elle ? 
Au départ j'ai cru que c'etait un retour d'etat du tag lorsque 'il vibre mais j'ai testé et ca ne bouge pas. 

<img width="500" alt="image" src="https://github.com/Minims/MyFox2MQTT/assets/54884656/b8c2f789-a376-4ec4-a889-500af036172b">
Merci

**Comment by Minims** [comment]
On a pas le retour sur le intellitag. 
C'est un reliquat du code de somfyProtect2MQTT que je n'ai pas nettoyé pour la version MyFox

**Comment by Minims** [comment]
je ne crée plus cette entité dans la 2023.10.1
